domain: mlflow
language: pytorch
project_slug: seg_training
project_slug_no_hyphen: seg_training
template_version: '1.0.0 # <<MLF-CORE_NO_BUMP>>'
template_handle: mlflow-pytorch
github_username: asd
creator_github_username: asd
is_github_repo: true
is_repo_private: true
is_github_orga: false
full_name: Dominik Jakob Molitoer
email: quit
project_name: seg_training
project_short_description: Segmentation training module for medical imaging
version: 0.1.0-SNAPSHOT
license: MIT
