name: histology_segmentation_training
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alembic=1.10.2
  - arrow-cpp=8.0.0
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - bcrypt=3.2.2
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.5
  - blosc=1.21.3
  - boost-cpp=1.70.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - configparser=5.3.0
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.3.1
  - databricks-cli=0.17.4
  - docker-py=6.0.0
  - eigen=3.4.0
  - entrypoints=0.4
  - ffmpeg=4.2.2
  - flask=2.2.3
  - fontconfig=2.13.94
  - fonttools=4.39.0
  - freetype=2.10.4
  - frozenlist=1.3.3
  - fsspec=2023.3.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.69.1
  - glog=0.6.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.16.2
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.14
  - greenlet=2.0.2
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gunicorn=20.1.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.0
  - importlib-metadata=6.0.0
  - importlib_resources=5.12.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.15
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcurl=7.87.0
  - libcxx=15.0.7
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm12=12.0.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - lightning-utilities=0.7.0
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - mako=1.2.4
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib-base=3.5.3
  - mdurl=0.1.0
  - mkl=2022.2.1
  - mlflow=2.2.1
  - multidict=6.0.4
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.0
  - ninja=1.11.1
  - nspr=4.35
  - nss=3.74
  - numba=0.56.4
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openblas=0.3.21
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - paramiko=3.0.0
  - partd=1.3.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.38.0
  - platformdirs=3.1.0
  - pooch=1.7.0
  - prometheus_client=0.16.0
  - prometheus_flask_exporter=0.22.3
  - protobuf=3.20.3
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-lightning=1.9.4
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - querystring_parser=1.2.4
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rich=13.3.2
  - rsa=4.9
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=65.6.3
  - shap=0.41.0
  - six=1.16.0
  - sleef=3.5.1
  - slicer=0.0.7
  - smmap=3.0.5
  - snappy=1.1.10
  - sqlalchemy=2.0.5.post1
  - sqlite=3.40.1
  - sqlparse=0.4.3
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.2
  - threadpoolctl=3.1.0
  - tifffile=2021.4.8
  - tk=8.6.12
  - toolz=0.12.0
  - torchmetrics=0.11.3
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - utf8proc=2.6.1
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.2
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
