accelerator: null
accumulate_grad_batches: null
alpha: 1
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
benchmark: null
check_val_every_n_epoch: 1
default_root_dir: null
detect_anomaly: false
devices: null
download: false
dropout_val: 0
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
epsilon: 1.0e-16
fast_dev_run: false
flat_weights: false
from_source: false
gamma_factor: 2.0
general_seed: 0
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
inference_mode: true
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
log_interval: 100
logger: true
lr: 0.01
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model: u2net
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 16
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
pytorch_seed: 0
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
strategy: null
sync_batchnorm: false
test_batch_size: 500
tpu_cores: null
track_grad_norm: -1
training_batch_size: 10
val_check_interval: null
weight_decay: 1.0e-05
